tr = input()

# Please write your code here.
q = [] 
count = 0 

for c in str :
            if(c == '(') :
                                    q.append(c) 
                                                            else :
                                                                                                    #q의 값이 있다면 
                                                                                                                                                if(len(q) > 0) :
                                                                                                                                                                                                                if(q[-1] == "(") :
                                                                                                                                                                                                                                                                                                    q.pop(-1)
                                                                                                                                                                                                                                                                                                                                                                                                else :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    q.append(c)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            #q의 값이 없다면 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                q.append(c)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(len(q) > 0) :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("No")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("Yes")



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                


